# For theme files see:
# https://github.com/catppuccin/alacritty

[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_latte.toml"
  # "~/.config/alacritty/themes/themes/catppuccin_macchiato.toml"
]

[font]
size = 14.0

[font.bold]
family = "Space Mono"
style = "Bold"

[font.bold_italic]
family = "Space Mono"
style = "Bold Italic"

[font.italic]
family = "Space Mono"
style = "Italic"

[font.normal]
family = "Space Mono"
style = "Regular"
